package dive

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class AirPocketTest
{
    private val idle = DiveInput.NONE

    @Test
    fun `same seed produces the same vents`() {
        val a = AirPocketField.generate(1L)
        val b = AirPocketField.generate(1L)
        assertEquals(a.size, b.size)
        a.indices.forEach {
            assertEquals(a[it].x, b[it].x, 0.0001f)
            assertEquals(a[it].depth, b[it].depth, 0.0001f)
        }
    }

    @Test
    fun `there is a vent in kelp twilight and trench`() {
        val zones = AirPocketField.generate(1L).map { it.zone }.toSet()
        assertEquals(setOf(Zone.KELP, Zone.TWILIGHT, Zone.TRENCH), zones)
    }

    @Test
    fun `there is deliberately no vent in the abyss`() {
        assertTrue(
            AirPocketField.generate(1L).none { it.zone == Zone.ABYSS },
            "the abyss must stay a gamble on the breath you arrive with"
        )
    }

    @Test
    fun `vents sit within the column bounds`() {
        AirPocketField.generate(3L).forEach {
            assertTrue(it.x in -Tuning.COLUMN_HALF_WIDTH..Tuning.COLUMN_HALF_WIDTH)
            assertTrue(it.depth in 0f..Tuning.MAX_DEPTH)
        }
    }

    // A test asserting exact-float-pair equality between vents and pearls used to live here
    // ("vent placement does not correlate with pearl placement"). It was deleted: vents and
    // pearls are generated by different formulas even when their RNG streams ARE correlated
    // (verified by setting AirPocketField's seed offset to plain `Random(seed)` — the test
    // still passed, because `x`/`depth` go through different arithmetic on each side, so an
    // exact float collision essentially never happens regardless of correlation). That made
    // the assertion incapable of failing, which is worse than no test — no meaningful,
    // non-white-box assertion of decorrelation was found, so this relies on
    // `same seed produces the same vents` for determinism instead. See AirPocketField's
    // seed-offset comment for the decorrelation intent itself.

    @Test
    fun `swimming into a vent refills the breath`() {
        val sim = DiveSim(seed = 1L)
        val vent = sim.airPockets.first()
        sim.debugMoveTo(vent.x, vent.depth)
        sim.debugSetAir(2f)

        sim.tick(1f / 60f, idle)

        assertTrue(sim.air > 25f, "air should be refilled, was ${sim.air}")
        assertTrue(vent.usedThisDive)
    }

    @Test
    fun `a vent only works once per dive`() {
        val sim = DiveSim(seed = 1L)
        val vent = sim.airPockets.first()
        sim.debugMoveTo(vent.x, vent.depth)
        sim.debugSetAir(2f)
        sim.tick(1f / 60f, idle)

        // Sit on the spent vent and let air drain.
        sim.debugMoveTo(vent.x, vent.depth)
        sim.debugSetAir(2f)
        repeat(30) { sim.tick(1f / 60f, idle) }

        assertTrue(sim.air < 2f, "a spent vent must not keep topping you up — that is camping")
    }

    @Test
    fun `surfacing rearms every vent for the next dive`() {
        val sim = DiveSim(seed = 1L)
        val vent = sim.airPockets.first()
        sim.debugMoveTo(vent.x, vent.depth)
        sim.debugSetAir(2f)
        sim.tick(1f / 60f, idle)
        assertTrue(vent.usedThisDive)

        sim.debugSurface()

        assertFalse(vent.usedThisDive, "a new dive must get the vents back")
    }

    @Test
    fun `a vent reached on the dying breath still saves the diver`() {
        val sim = DiveSim(seed = 1L)
        val vent = sim.airPockets.first()
        sim.debugMoveTo(vent.x, vent.depth)
        sim.debugSetHeld(count = 900, mass = 0f)
        sim.debugSetAir(0.001f)   // would black out this very tick

        sim.tick(1f / 60f, idle)

        assertEquals(900, sim.held, "the vent must be checked before air burns, not after")
        assertEquals(0, sim.banked, "no blackout bank should have happened")
    }

    @Test
    fun `an EMPTY diver is reachable and returnable from the trench vent`() {
        // This only demonstrates the empty-handed case, which is worth zero — see the
        // laden-diver test below for the case the mechanic actually exists to serve.
        val sim = DiveSim(seed = 1L)
        sim.pearls.forEach { it.collected = true }
        val trenchVent = sim.airPockets.first { it.zone == Zone.TRENCH }

        sim.debugMoveTo(trenchVent.x, trenchVent.depth)
        sim.debugSetAir(1f)
        sim.tick(1f / 60f, idle)          // refill at the vent

        // Now swim all the way up on that breath.
        val up = DiveInput(0f, -1f, kick = false, bleed = false)
        var ticks = 0
        while (sim.depth > 0.5f && ticks < 60 * 60) { sim.tick(1f / 60f, up); ticks++ }

        assertTrue(sim.depth <= 0.5f, "diver failed to reach the surface from the trench vent")
        assertFalse(sim.blackedOut, "the ascent from a refilled trench vent must be survivable")
    }

    @Test
    fun `a laden diver can return from the trench vent`() {
        val sim = DiveSim(seed = 1L)
        sim.pearls.forEach { it.collected = true }
        val vent = sim.airPockets.first { it.zone == Zone.TRENCH }
        sim.debugMoveTo(vent.x, vent.depth)
        sim.debugSetHeld(count = 600, mass = 32f)   // four trench pearls, the smallest haul worth the trip
        sim.tick(1f / 60f, DiveInput.NONE)          // refill at the vent

        val up = DiveInput(0f, -1f, kick = false, bleed = false)
        var ticks = 0
        while (sim.depth > 0.5f && !sim.blackedOut && ticks < 60 * 90) { sim.tick(1f / 60f, up); ticks++ }

        assertFalse(sim.blackedOut, "a laden diver must be able to get home from the trench vent")
    }
}
